design_task:
  description: >
    Take the high level requirements described here and prepare a detailed design for both backend and frontend deliverables.
    Backend: 1 Python module, outline the classes and methods.
    Frontend: 1 self-contained HTML file (optionally with small inline CSS/JS) describing key sections, components and interactions.
    Here are the requirements: {requirements}
    IMPORTANT: Output ONLY markdown. Include two sections: "Backend Design" and "Frontend Design" with clear bullet points and file names.
  expected_output: >
    A detailed markdown design doc with sections for backend and frontend.
  agent: engineering_lead
  output_file: output/{module_name}_design.md

code_task:
  description: >
    Write a python module that implements the design described by the engineering lead, in order to achieve the requirements.
    Here are the requirements: {requirements}
  expected_output: >
    A python module that implements the design and achieves the requirements.
    IMPORTANT: Output ONLY the raw Python code without any markdown formatting, code block delimiters, or backticks.
    The output should be valid Python code that can be directly saved to a file and executed.
  agent: backend_engineer
  context:
    - design_task
  output_file: output/{module_name}

frontend_task:
  description: >
    Produce a self-contained, production-ready HTML5 file named index.html that implements the frontend design.
    - Use semantic HTML and simple, modern CSS inside a <style> in the <head>.
    - If needed, add a minimal <script> at the end of <body> with vanilla JS.
    - The page must be responsive (mobile-first) and accessible (labels, alt text, sensible headings).
    - If the backend module {module_name} is relevant, include example JSON blocks or code snippets showing how it would integrate, but do not import Python in HTML.
    Here are the requirements: {requirements}
  expected_output: >
    A single raw HTML document for index.html.
    IMPORTANT: Output ONLY valid HTML content with <!doctype html> at the top, no markdown, no backticks, no extra text.
  agent: frontend_engineer
  context:
    - design_task
  output_file: output/index.html

